#!/usr/bin/env bash
# Installs nginx on my web-01 server
apt-get -y update
apt-get install -y nginx
# installs nginx
ufw allow 'Nginx HTTP'
# allows nginx on firewall
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
# writes hello world into te html file
service nginx restart
