#!/usr/bin/env bash
# performs various configurations in the web server

sudo apt-get -y update
sudo sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
# installs nginx
sudo chmod -R 777 /var/www
sudo chmod -R 777 /etc/nginx
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.bckup
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
# overwrrite that index file
sudo echo -e \
     "http { 
     	   server {
           listen 80 default_server;
           listen [::]:80 default_server;

           root /var/www/html;
           index index.html index.htm index.nginx-debian.html;

           server_name _;

           location / {
	   	    return 301;
        	    }
		    # if location is redirect me
}
}
events {}" > /etc/nginx/nginx.conf
# write the following configurations in nginx config
sudo service nginx start
