#!/usr/bin/env bash
# performs various configurations in the web server

sudo apt-get -y update
sudo sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
# installs nginx
sudo chmod -R 777 /var/www
sudo chmod -R 777 /etc/nginx
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.bckup
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
# overwrrite that index file
sudo echo -e \
     "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
	location = /redirect_me/ {
		 return 301 $scheme://www.youtube.com/watch?v=QH2-TGUlwu4$request_uri;
	}
}" > /etc/nginx/sites-available/default
# second location redirects if file location requested is redirect_me
# write the above configurations in nginx sites-available and restart nginx to save changes
sudo service nginx restart
