#!/usr/bin/env bash
# a script that installs and configures HAProxy

# install HAProxy
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.7 -y
apt-get update -y
apt-get install -y haproxy=2.7.\*

# configurations

# make HAProxy load balancer to start automatically when the system boots.
echo "ENABLED=1" >> /etc/default/haproxy
# configuration in haproxy config file
echo -e "

frontend mywebservers
   bind *:80
   default_backend mywebservers

backend mywebservers
   balance roundrobin
   mode http
   server server1 100.25.41.245:80 check
   server server2 54.172.27.227:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy start 
service haproxy restart
