#!/usr/bin/env bash
# make nginx run and listen on port 80

# make nginx listen to the servers in sites-available instead
sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
service nginx restart
