#!/usr/bin/env bash
# make nginx run and listen on port 80

# create a symlink between sites-available and sites-enabled because
# some sites available are not enabled which include one listening on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default 
service nginx restart
