#!/usr/bin/env bash
#learning to use case

i=1
while(("$i" < 21)); do
    case $i in
    4)
    echo 4
    echo "bad luck from China"
    ;;
    9)
    echo 9
    echo "bad luck from Japan"
    ;;
    17)
    echo 17
    echo "bad luck from Italy"
    ;;
    *)
    echo "$i"
    ;;
    esac
    ((i++))
done
