#!/usr/bin/env bash
# debugging nginx, changing nginx to be run by nginx user
sed -i "s/#user www-data;/user nginx nginx;/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
# start the nginx service as the nginx user
sudo -u nginx service nginx start
