#!/usr/bin/env bash
# debugging nginx, changing nginx to be run by nginx user
sudo service nginx start
sed -i "s/#user www-data;/user nginx nginx;/g" /etc/nginx/nginx.conf
sudo service nginx restart
sudo nginx -s reload
