#!/usr/bin/env bash
# debugging nginx, changing nginx to be run by nginx user
sudo service nginx start
sed -i "s/#user www-data;/user nginx nginx;" /etc/nginx/nginx.conf

# adding a server block that listes on port 8080
echo -e "server {
   listen 8080 default_server;
   listen [::]:8080 default_server;
   server_name _;
   root html;
   index index.html index.htm index.nginx-debian.html;

   location / {
       try_files index.nginx-debian.html/ =404;
   }
}" >> /etc/nginx/sites-available/default
sudo nginx -s reload
sudo service nginx restart
